#!/usr/bin/env bash
#SBATCH -A NAISS2024-1-24 -p alvis
#SBATCH -t 0-12:00:00
#SBATCH -N 1 --gpus-per-node=A100:4
#SBATCH --error=/mimer/NOBACKUP/groups/alvis_cvl/hannahhe/UQ_Proj/outs/%j-%x.err
#SBATCH --output=/mimer/NOBACKUP/groups/alvis_cvl/hannahhe/UQ_Proj/outs/%j-%x.out
#SBATCH --job-name='VAD_nuscenes_collection'

T=`date +%m%d%H%M`

# -------------------------------------------------- #
# Usually you only need to customize these variables #
CFG=projects/configs/VAD/VAD_base.py                 #
GPUS=4                                               #
# -------------------------------------------------- #
GPUS_PER_NODE=4
NNODES=1

MASTER_PORT=${MASTER_PORT:-28596}
MASTER_ADDR=${MASTER_ADDR:-"127.0.0.1"}
RANK=${RANK:-0}

WORK_DIR=/mimer/NOBACKUP/groups/alvis_cvl/hannahhe/UQ_Proj/outs/slurm/$T

singularity exec --nv --pwd /mimer/NOBACKUP/groups/alvis_cvl/hannahhe/UQ_Proj/VAD \
/mimer/NOBACKUP/groups/alvis_cvl/hannahhe/UQ_Proj/vad_will.sif  \
python -m torch.distributed.launch \
    --nproc_per_node=${GPUS_PER_NODE} \
    --master_addr=${MASTER_ADDR} \
    --master_port=${MASTER_PORT} \
    --nnodes=${NNODES} \
    --node_rank=${RANK} \
    tools/train.py \
    $CFG \
    --launcher pytorch  \
    --load-from ckpts/VAD_base.pth\
    --work-dir ${WORK_DIR}

